include armv6 arch when building static lib
The definition of $(ARCHS_STANDARD_32_BIT) no longer includes the arm6
architecture. It should be added explicitly to avoid warnings and/or
compilation errors like "Undefined symbols for architecture armv6:
  .........
ld: symbol(s) not found for architecture armv6"