Update CHANGELOG.md to note that the Facebook SDK now requires Xcode 13
Summary:
Building with Xcode 12 shows the following build failure:

```
error: failed to build module 'FBSDKCoreKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
```

This was reported in:
https://github.com/facebook/facebook-ios-sdk/issues/1911

Reviewed By: samodom

Differential Revision: D31715980

fbshipit-source-id: 2c78ea224e43f3f808ac8a8f503019d972182c77