[FBSDKiOS] Fix the test error caused by ambiguous URLSchema type in swift
Summary:
## Context
We saw some errors in the FBSDK iOS codebase

## Root cause
URLScheme have been defined in both FBSDKCoreKit and WebKit.

## Fix
Rename the NS_SWIFT_NAME for FBSDKURLScheme from URLScheme to URLSchemeEnum to disambiguate them

## Ref
Raw error log
```
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:49:13: error: 'URLScheme' is ambiguous for type lookup in this context
    scheme: URLScheme = .https
            ^~~~~~~~~
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKit/include/FBSDKURLScheme.h:11:19: note: found this candidate
typedef NSString *FBSDKURLScheme NS_TYPED_EXTENSIBLE_ENUM NS_SWIFT_NAME(URLScheme);
                  ^
WebKit.URLScheme:4:15: note: found this candidate
public struct URLScheme : Hashable, Sendable {
              ^
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:78:34: error: cannot infer contextual base in reference to member 'native'
      makeRequest(protocolType: .native, scheme: .facebookAPI),
                                ~^~~~~~
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:78:51: error: cannot infer contextual base in reference to member 'facebookAPI'
      makeRequest(protocolType: .native, scheme: .facebookAPI),
                                                 ~^~~~~~~~~~~
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:84:23: error: generic parameter 'T' could not be inferred
    let request = try XCTUnwrap(makeRequest())
                      ^
XCTest.XCTUnwrap:1:13: note: in call to function 'XCTUnwrap(_:_:file:line:)'
public func XCTUnwrap<T>(_ expression: @autoclosure () throws -> T?, _ message: @autoclosure () -> String = "", file: StaticString = #filePath, line: UInt = #line) throws -> T
            ^
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:86:43: error: type 'Equatable' has no member 'web'
    XCTAssertEqual(request.protocolType, .web, "A request should use the provided protocol type")
                                         ~^~~
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:91:37: error: type 'Equatable' has no member 'https'
    XCTAssertEqual(request.scheme, .https, "A request should use the provided scheme")
                                   ~^~~~~
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:95:26: error: generic parameter 'T' could not be inferred
    let parameters = try XCTUnwrap(request.parameters, parametersMessage)
                         ^
XCTest.XCTUnwrap:1:13: note: in call to function 'XCTUnwrap(_:_:file:line:)'
public func XCTUnwrap<T>(_ expression: @autoclosure () throws -> T?, _ message: @autoclosure () -> String = "", file: StaticString = #filePath, line: UInt = #line) throws -> T
            ^
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:100:24: error: generic parameter 'T' could not be inferred
    let userInfo = try XCTUnwrap(request.userInfo, userInfoMessage)
                       ^
XCTest.XCTUnwrap:1:13: note: in call to function 'XCTUnwrap(_:_:file:line:)'
public func XCTUnwrap<T>(_ expression: @autoclosure () throws -> T?, _ message: @autoclosure () -> String = "", file: StaticString = #filePath, line: UInt = #line) throws -> T
            ^
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:106:23: error: generic parameter 'T' could not be inferred
    let request = try XCTUnwrap(makeRequest())
                      ^
XCTest.XCTUnwrap:1:13: note: in call to function 'XCTUnwrap(_:_:file:line:)'
public func XCTUnwrap<T>(_ expression: @autoclosure () throws -> T?, _ message: @autoclosure () -> String = "", file: StaticString = #filePath, line: UInt = #line) throws -> T
            ^
/data/sandcastle/boxes/trunk-git-facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKitTests/Internal/BridgeAPI/BridgeAPIRequestTests.swift:116:23: error: generic parameter 'T' could not be inferred
    let request = try XCTUnwrap(makeRequest())
```

Test Plan:
# app build
build coffee shop without problems

# Format
./internal/tools/swiftformat .

# unit test
unit tests CI signals
 {F1983106517}

Rollback Plan:

Reviewers: maxalbright, #app_signals, kongxinzhu

Reviewed By: maxalbright

Differential Revision: https://phabricator.intern.facebook.com/D85775584

Tags: opensource-needs-export, risk_score_signal